[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum_sepolia = { key = "${ARBITRUM_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
